# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{whatismyip}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jimmy Baker"]
  s.date = %q{2010-01-11}
  s.default_executable = %q{whatismyip}
  s.description = %q{Lets you check your ip address by simply}
  s.email = %q{jimmybaker@me.com}
  s.executables = ["whatismyip"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/whatismyip",
     "lib/whatismyip.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/whatismyip_spec.rb",
     "whatismyip.gemspec"
  ]
  s.homepage = %q{http://github.com/jumzies/whatismyip}
  s.post_install_message = %q{Now simply type 'whatismyip'..}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{The simple way to check your ip addresses from the command line.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/whatismyip_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

